import React, { useEffect, useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useNavigation, useRoute } from "@react-navigation/native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { colors, spacing, useThemedColors } from "../theme";
import { ScreenContainer } from "../components/common/ScreenContainer";
import { BackButton } from "../components/common/BackButton";
import * as reportsApi from "../api/reports";
import { WeeklyReportDetail } from "../types/report";
import { useUserStore } from "../stores/userStore";
import { getCurrencySymbol } from "../utils/currency";

const WeeklyReportScreen = () => {
  const themedColors = useThemedColors();
  const navigation = useNavigation();
  const route = useRoute<any>();
  const { reportId } = route.params as { reportId: string };
  const { user } = useUserStore();

  const [report, setReport] = useState<WeeklyReportDetail | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isExporting, setIsExporting] = useState(false);

  const symbol = getCurrencySymbol(user?.userPrefs?.currency ?? "USD");

  useEffect(() => {
    reportsApi
      .getReportById(reportId)
      .then(setReport)
      .catch(() => navigation.goBack())
      .finally(() => setIsLoading(false));
  }, [reportId]);

  const formatDateRange = (start: string, end: string) => {
    const s = new Date(start).toLocaleDateString("en-US", { month: "short", day: "numeric" });
    const e = new Date(end).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
    return `${s} – ${e}`;
  };

  const handleExportPdf = async () => {
    if (!report) return;
    setIsExporting(true);
    try {
      const dateRange = formatDateRange(report.weekStart, report.weekEnd);
      const html = `
        <html><body style="font-family:sans-serif;padding:24px;max-width:600px;margin:auto">
          <h1 style="color:#2D9CDB">AI Finance Coach</h1>
          <h2>Weekly Report</h2>
          <p style="color:#888">${dateRange}</p>
          <hr/>
          <h3>Summary</h3>
          <ul>
            <li><strong>Total Spent:</strong> ${symbol}${report.totalSpent.toFixed(2)}</li>
            <li><strong>Transactions:</strong> ${report.txCount}</li>
            <li><strong>Top Category:</strong> ${report.topCategory}</li>
          </ul>
          <h3>Coach's Notes</h3>
          <p>${report.aiSummary}</p>
          <p style="color:#aaa;font-size:12px;margin-top:40px">Generated by AI Finance Coach</p>
        </body></html>
      `;
      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, {
        mimeType: "application/pdf",
        UTI: "com.adobe.pdf",
      });
    } catch {
      // sharing cancelled or failed silently
    } finally {
      setIsExporting(false);
    }
  };

  if (isLoading) {
    return (
      <ScreenContainer backgroundColor={themedColors.background}>
        <ActivityIndicator color={colors.primary} style={{ marginTop: 60 }} />
      </ScreenContainer>
    );
  }

  if (!report) return null;

  return (
    <ScreenContainer backgroundColor={themedColors.background}>
      <View style={[styles.header, { borderBottomColor: themedColors.border }]}>
        <BackButton />
        <Text style={[styles.headerTitle, { color: themedColors.textPrimary }]}>
          Weekly Report
        </Text>
        <TouchableOpacity
          onPress={handleExportPdf}
          disabled={isExporting}
          style={styles.exportBtn}
        >
          {isExporting ? (
            <ActivityIndicator size="small" color={colors.primary} />
          ) : (
            <Ionicons name="download-outline" size={24} color={colors.primary} />
          )}
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={styles.content}>
        <Text style={[styles.dateRange, { color: themedColors.textSecondary }]}>
          {formatDateRange(report.weekStart, report.weekEnd)}
        </Text>

        <View style={styles.statsRow}>
          {[
            { label: "Total Spent", value: `${symbol}${report.totalSpent.toFixed(2)}`, color: colors.error },
            { label: "Transactions", value: String(report.txCount), color: colors.primary },
            { label: "Top Category", value: report.topCategory, color: colors.accent },
          ].map((s) => (
            <View
              key={s.label}
              style={[styles.statCard, { backgroundColor: themedColors.surface }]}
            >
              <Text style={[styles.statValue, { color: s.color }]}>{s.value}</Text>
              <Text style={[styles.statLabel, { color: themedColors.textSecondary }]}>
                {s.label}
              </Text>
            </View>
          ))}
        </View>

        <View style={[styles.summaryCard, { backgroundColor: themedColors.surface }]}>
          <View style={styles.coachHeader}>
            <View style={[styles.coachDot, { backgroundColor: colors.primary }]}>
              <Ionicons name="sparkles" size={14} color="#fff" />
            </View>
            <Text style={[styles.coachName, { color: colors.primary }]}>Coach's Notes</Text>
          </View>
          <Text style={[styles.summaryText, { color: themedColors.textPrimary }]}>
            {report.aiSummary}
          </Text>
        </View>

        <TouchableOpacity
          style={[styles.downloadBtn, { borderColor: colors.primary }]}
          onPress={handleExportPdf}
          disabled={isExporting}
        >
          <Ionicons name="document-outline" size={18} color={colors.primary} />
          <Text style={[styles.downloadBtnText, { color: colors.primary }]}>
            {isExporting ? "Exporting..." : "Download PDF"}
          </Text>
        </TouchableOpacity>

        <View style={{ height: 40 }} />
      </ScrollView>
    </ScreenContainer>
  );
};

const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 17,
    fontWeight: "700",
    fontFamily: "RobotoMono-Bold",
  },
  exportBtn: { width: 40, alignItems: "flex-end" },
  content: { padding: 16 },
  dateRange: { fontSize: 14, marginBottom: 16, fontFamily: "RobotoMono-Regular" },
  statsRow: { flexDirection: "row", gap: 8, marginBottom: 16 },
  statCard: { flex: 1, borderRadius: 16, padding: 12, alignItems: "center", gap: 4 },
  statValue: { fontSize: 15, fontWeight: "700", fontFamily: "RobotoMono-Bold", textAlign: "center" },
  statLabel: { fontSize: 10, textTransform: "uppercase", fontFamily: "RobotoMono-Regular" },
  summaryCard: { borderRadius: 16, padding: 16, marginBottom: 16 },
  coachHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 12 },
  coachDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  coachName: { fontSize: 14, fontWeight: "700", fontFamily: "RobotoMono-Bold" },
  summaryText: { fontSize: 14, lineHeight: 22, fontFamily: "RobotoMono-Regular" },
  downloadBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1.5,
    borderRadius: 30,
    paddingVertical: 14,
  },
  downloadBtnText: { fontSize: 15, fontWeight: "700", fontFamily: "RobotoMono-Bold" },
});

export default WeeklyReportScreen;
